// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbr8Q7Bj7k-Cz4ubNnfFdLRCkHKJE7ps',
    appId: '1:758148089896:web:c6df28df67f312f5918d1d',
    messagingSenderId: '758148089896',
    projectId: 'tugas-sherlyn-2327240134',
    authDomain: 'tugas-sherlyn-2327240134.firebaseapp.com',
    databaseURL: 'https://tugas-sherlyn-2327240134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-sherlyn-2327240134.firebasestorage.app',
    measurementId: 'G-0GFXZQCGW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZDksGjArO0ZbZ10SPccMej5JnoTJPV8',
    appId: '1:758148089896:android:9e705ce3344291d3918d1d',
    messagingSenderId: '758148089896',
    projectId: 'tugas-sherlyn-2327240134',
    databaseURL: 'https://tugas-sherlyn-2327240134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-sherlyn-2327240134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rFqtevc8EtDIopCC2GlPRzsy_d6zlb4',
    appId: '1:758148089896:ios:55296b7b9b5fd452918d1d',
    messagingSenderId: '758148089896',
    projectId: 'tugas-sherlyn-2327240134',
    databaseURL: 'https://tugas-sherlyn-2327240134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-sherlyn-2327240134.firebasestorage.app',
    iosBundleId: 'com.example.tugasSherlyn2327240134',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rFqtevc8EtDIopCC2GlPRzsy_d6zlb4',
    appId: '1:758148089896:ios:55296b7b9b5fd452918d1d',
    messagingSenderId: '758148089896',
    projectId: 'tugas-sherlyn-2327240134',
    databaseURL: 'https://tugas-sherlyn-2327240134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-sherlyn-2327240134.firebasestorage.app',
    iosBundleId: 'com.example.tugasSherlyn2327240134',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbr8Q7Bj7k-Cz4ubNnfFdLRCkHKJE7ps',
    appId: '1:758148089896:web:2d4073e785759b5d918d1d',
    messagingSenderId: '758148089896',
    projectId: 'tugas-sherlyn-2327240134',
    authDomain: 'tugas-sherlyn-2327240134.firebaseapp.com',
    databaseURL: 'https://tugas-sherlyn-2327240134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-sherlyn-2327240134.firebasestorage.app',
    measurementId: 'G-30LQCQC3ZD',
  );

}